# -*- coding: utf-8 -*-
"""
File read/write utilities.

Functions
---------
open_dlc_h5(dlc_path, h5key=None)
    Open the .h5 file generated by DLC.
write_h5(filename, dic)
    Write a dictionary to an .h5 file.
recursively_save_dict_contents_to_group(h5file, path, dic)
    Recursively save dictionary contents to a group in an .h5 file. This is
    not accessible from outside the module.
recursively_load_dict_contents_from_group(h5file, path)
    Recursively load dictionary contents from a group in an .h5 file. This is
    not accessible from outside the module.
read_h5(filename, ASLIST=False)
    Read an .h5 file in as a dictionary.
read_yaml(path)
    Read a .yaml file.
write_yaml(path, contents)
    Write a .yaml file.


Author: DMM, 2024
"""

import json
import yaml
import h5py
import datetime
import numpy as np
import pandas as pd

from .time import time2str


def open_dlc_h5(dlc_path, h5key=None):
    
    if h5key is None:
        pts = pd.read_hdf(dlc_path)
    else:
        pts = pd.read_hdf(dlc_path, key=h5key)
    pts.columns = [' '.join(col[:][1:3]).strip() for col in pts.columns.values]
    pts = pts.rename(columns={pts.columns[n]: pts.columns[n].replace(' ', '_') for n in range(len(pts.columns))})
    pt_loc_names = pts.columns.values
    return pts, pt_loc_names


def write_h5(filename, dic):

    with h5py.File(filename, 'w') as h5file:
        recursively_save_dict_contents_to_group(h5file, '/', dic)


def recursively_save_dict_contents_to_group(h5file, path, dic):

    if isinstance(dic,dict):
        iterator = dic.items()
    elif isinstance(dic,list):
        iterator = enumerate(dic)
    else:
        ValueError('Cannot save %s type' % type(dic))
    for key, item in iterator:
        key = str(key) 
        if isinstance(item, (np.ndarray, np.number, np.bool_, int, float, str, bytes, bool)):
            try:
                h5file[path + key] = item
            except TypeError:
                if isinstance(item, np.ndarray) and (item.dtype == object):
                    recursively_save_dict_contents_to_group(h5file, path + key + '/', item.item())
        elif isinstance(item, dict) or isinstance(item, list):
            recursively_save_dict_contents_to_group(h5file, path + key + '/', item)
        elif isinstance(item, datetime.datetime):
             h5file[path + key] = time2str(item)
        else:
            raise ValueError('Cannot save %s type'%type(item))


def recursively_load_dict_contents_from_group(h5file, path):
    
    ans = {}
    for key, item in h5file[path].items():
        if isinstance(item, h5py._hl.dataset.Dataset):
            ans[key] = item[()]
        elif isinstance(item, h5py._hl.group.Group):
            ans[key] = recursively_load_dict_contents_from_group(
                h5file,
                path + key + '/'
            )

    return ans


def read_h5(filename, aslist=False):

    with h5py.File(filename, 'r') as h5file:
        out = recursively_load_dict_contents_from_group(h5file, '/')
        if aslist:
            outl = [None for l in range(len(out.keys()))]
            for key, item in out.items():
                outl[int(key)] = item
            out = outl

        return out
    

def read_yaml(path):

    with open(path, 'r') as infile:
        try:
            contents = yaml.load(infile, Loader=yaml.FullLoader)
        except yaml.constructor.ConstructorError:
            infile.seek(0)
            contents = yaml.load(infile, Loader=yaml.UnsafeLoader)

    return contents


def write_yaml(path, contents):

    with open(path, 'w') as outfile:
        yaml.dump(contents, outfile, default_flow_style=False)



def write_group_h5(df, savepath, repair_overflow=False):

    if repair_overflow:
        df = normalize_for_hdf(fix_overflow_columns(df))
    split_key = 'base_name'
    split_list = df[split_key].unique()
    for i, sname in enumerate(split_list):
        print('Writing block {} of {} (key={})'.format(i+1, len(split_list), sname))
        df[df[split_key]==sname].to_hdf(savepath, sname, mode='a')


def get_group_h5_keys(savepath):

    with pd.HDFStore(savepath) as hdf:
        keys = [k.replace('/','') for k in hdf.keys()]

    return keys


def read_group_h5(path, keys=None):

    if type(keys) == str:
        df = pd.read_hdf(path, keys)
        return df
    if keys is None:
        keys = get_group_h5_keys(path)
    dfs = []
    for k in sorted(keys):
        _df = pd.read_hdf(path, k) 
        dfs.append(_df)
    df = pd.concat(dfs)

    return df

def find_hdf_overflow_columns(df):

    bad_cols = []
    for col in df.columns:
        s = df[col]
        if pd.api.types.is_integer_dtype(s):
            if (s.min() < np.iinfo(np.int64).min) or (s.max() > np.iinfo(np.int64).max):
                bad_cols.append(col)
        elif pd.api.types.is_object_dtype(s):
            if s.apply(lambda x: isinstance(x, int) and (x > np.iinfo(np.int64).max or x < np.iinfo(np.int64).min)).any():
                bad_cols.append(col)
                
    return bad_cols


def fix_overflow_columns(df):

    bad_cols = find_hdf_overflow_columns(df)
    if not bad_cols:
        return df
    df_fixed = df.copy()
    for col in bad_cols:
        print(f"Converting column '{col}' to string (values exceed int64 range).")
        df_fixed[col] = np.clip(df_fixed[col], np.iinfo(np.int64).min, np.iinfo(np.int64).max).astype("int64")

    return df_fixed

def normalize_for_hdf(df):

    INT64_MIN, INT64_MAX = np.iinfo(np.int64).min, np.iinfo(np.int64).max
    df_fixed = df.copy()
    try:
        if df_fixed.index.dtype == object or pd.api.types.is_integer_dtype(df_fixed.index):
            if getattr(df_fixed.index, "min", lambda: 0)() < INT64_MIN or getattr(df_fixed.index, "max", lambda: 0)() > INT64_MAX:
                print("Converting index to string (too large for int64).")
                df_fixed.index = df_fixed.index.astype(str)
    except Exception:
        df_fixed.index = df_fixed.index.astype(str)
    for col in df_fixed.columns:
        s = df_fixed[col]
        if pd.api.types.is_integer_dtype(s):
            if (s.min() < INT64_MIN) or (s.max() > INT64_MAX):
                print(f"Column '{col}' too large — converting to string.")
                df_fixed[col] = s.astype(str)
        elif pd.api.types.is_object_dtype(s):
            def clean(x):
                if isinstance(x, int) and not (INT64_MIN <= x <= INT64_MAX):
                    return str(x)
                if isinstance(x, (dict, list, tuple)):
                    return json.dumps(x)
                try:
                    str(x)
                    return x
                except Exception:
                    return repr(x)
            df_fixed[col] = s.map(clean).astype(str)
    return df_fixed


def read_json(file_path):
    with open(file_path, 'r') as file:
        data = json.load(file)
    return data